/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdvancedDatePickerComponent: typeof import('./src/components/AdvancedDatePickerComponent.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BFormFloatingLabel: typeof import('bootstrap-vue-next')['BFormFloatingLabel']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BToaster: typeof import('bootstrap-vue-next')['BToaster']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    BusinessTaskEditorComponent: typeof import('./src/components/BusinessTaskEditorComponent.vue')['default']
    CreateBusinessTaskButtonComponent: typeof import('./src/components/CreateBusinessTaskButtonComponent.vue')['default']
    EditIconComponent: typeof import('./src/components/EditIconComponent.vue')['default']
    LoadingButton: typeof import('./src/components/LoadingButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleComponent: typeof import('./src/components/ScheduleComponent.vue')['default']
    TrashIconComponent: typeof import('./src/components/TrashIconComponent.vue')['default']
    ZoomInIconComponent: typeof import('./src/components/ZoomInIconComponent.vue')['default']
    ZoomOutIconComponent: typeof import('./src/components/ZoomOutIconComponent.vue')['default']
    ZoomResetIconComponent: typeof import('./src/components/ZoomResetIconComponent.vue')['default']
  }
}
