name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - run: npm ci
    - run: npm run build
    - run: cargo install tauri-cli
    - run: cargo tauri build
    - if: matrix.platform == 'windows-latest'
      run: cargo tauri build --target aarch64-pc-windows-msvc
    - if: matrix.platform == 'macos-latest'
      run: cargo tauri build --target aarch64-apple-darwin
